name: Run Tests, Draft Release and Deploy to PyPi Test
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./src
          pip install -r requirements.txt
          pip install -U -r requirements-dev.txt
      - name: Run tests with pytest
        run: |
          pytest --cache-clear --cov=motu_server > pytest-coverage.txt
      - name: Comment Coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
  update_release_draft:
    if: github.repository == 'ChristopherJohnston/motu_osc_bridge'
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-to-pypi:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
      run: |
        python -m build ./src
        twine upload -r testpypi ./src/dist/*